#!/usr/bin/env python3

import configparser
import json
import docker
import etcd
from flask import Flask, request


# INITIALIZATION
#-----------------------------------------------------------------------------------------------------

# DATA STRUCTURE 'cloud_info'
cloud_info = {}
#
# {
#   "application_name1":
#   {
#     "containers":
#     {
#       "id1":
#       (container_object, {internal_port1:host_port1, ...})
#       ...
#     }
#     "load_balancers":
#     {
#       TODO
#     }
#   }
#   ...
# }
#
# etcd equivalent of cloud_info:
# /mycloud/
# /mycloud/application_name1/
# /mycloud/application_name1/containers/
# /mycloud/application_name1/containers/(id1:port_map_str)
# /mycloud/application_name1/load_balancers/TODO

config = configparser.ConfigParser()
config.read("config.ini")

docker_client = docker.from_env()
docker_client.containers.prune() # remove all non-running containers

etcd_client = etcd.Client()

# populate cloud_info using etcd
mycloud_exists = False
try:
    etcd_client.read("/mycloud", dir=True)
    mycloud_exists = True
except etcd.EtcdKeyNotFound:
    etcd_client.write("/mycloud", None, dir=True)

def children_of_dir_read_result(dir_read_result):
    if next(dir_read_result.leaves) is dir_read_result: return []
    else: return list(dir_read_result.leaves)

if mycloud_exists:
    mycloud_dir = etcd_client.read('/mycloud', dir=True)

    for app_dir in children_of_dir_read_result(mycloud_dir):
        app_dir = etcd_client.read(app_dir.key, dir=True)

        [containers_dir, load_balancers_dir] = children_of_dir_read_result(app_dir)
        containers_dir     = etcd_client.read(containers_dir.key,     dir=True)
        load_balancers_dir = etcd_client.read(load_balancers_dir.key, dir=True)

        app_name = app_dir.key.split('/')[-1]
        cloud_info[app_name] = {"containers": {}, "load_balancers": {}}

        for container_file in children_of_dir_read_result(containers_dir):
            container_id = container_file.key.split('/')[-1]

            try:
                container = docker_client.containers.get(container_id) # throws NotFound
                port_map = eval(container_file.value)
                cloud_info[app_name]["containers"][container_id] = (container, port_map)
            except docker.errors.NotFound:
                print("container: "+container_id+" not found")
                etcd_client.delete("/mycloud/"+app_name+"/containers/"+container_id, recursive=True)

        # TODO: load balancers

def set_of_container_ids(cloud_info):
    container_ids = set()

    mycloud_dir = etcd_client.read('/mycloud', dir=True)

    for app_dir in children_of_dir_read_result(mycloud_dir):
        app_dir = etcd_client.read(app_dir.key, dir=True)

        [containers_dir, load_balancers_dir] = children_of_dir_read_result(app_dir)
        containers_dir     = etcd_client.read(containers_dir.key,     dir=True)

        for container_file in children_of_dir_read_result(containers_dir):
            container_id = container_file.key
            container_ids.add(container_id)

    return container_ids

# kill containers not in cloud_info
def kill_unrecorded_containers(cloud_info):
    recorded_container_ids = set_of_container_ids(cloud_info)

    for container in docker_client.containers.list(all=True):
        if container.id not in recorded_container_ids:
            try: container.kill()
            except: print("container "+container.id+" died before killing it")

kill_unrecorded_containers(cloud_info)

# TODO dont remove containers from etcd unless you search for them and they're dead


# DOCKER HELPERS
#-----------------------------------------------------------------------------------------------------

def show_all_containers(all_containers=False):
    return docker_client.containers.list(all=all_containers)

def kill_all_not_running():
    docker_client.containers.prune()

def kill_by_id(*ids):
    fltr = {"id":i for i in ids}
    docker_client.containers.prune(fltr)


# SERVER HELPERS
#-----------------------------------------------------------------------------------------------------

def create_command(req):
    if "app_name" not in req:
        return "create: app_name required"
    app_name = req["app_name"]

    # put app_name in cloud_info
    if app_name in cloud_info:
        return "create: app "+app_name+" already exists"
    cloud_info[app_name] = {"containers": {}, "load_balancers": {}}

    # put app_name in etcd
    try:
        etcd_client.read("/mycloud/"+app_name, dir=True)
        return "create: app "+app_name+" already exists in etcd"
    except etcd.EtcdKeyNotFound: pass
    etcd_client.write("/mycloud/"+app_name,                   None, dir=True)
    etcd_client.write("/mycloud/"+app_name+"/containers",     None, dir=True)
    etcd_client.write("/mycloud/"+app_name+"/load_balancers", None, dir=True)

    return "create successful"

def run_command(req):
    if "app_name" not in req:
        return "run: app_name required"
    app_name = req["app_name"]
    if app_name not in cloud_info:
        return "run: app_name not found, must create app first"

    if "command_string" not in req:
        return "run: command_string required"
    command_string = req["command_string"]

    port_map = {}
    if "port_map" in req:
        port_map = eval(req["port_map"])

    try:
        container = docker_client.containers.run(
            "ubuntu",
            command_string,
            remove=True,
            detach=True # TODO: actually use port_map
        )
    except Exception as e:
        return "run: failed: "+str(e)

    # put container_id in cloud_info
    cloud_info[app_name]["containers"][container.id] = (container, port_map)

    # put container_id in etcd
    etcd_client.write("/mycloud/"+app_name+"/containers/"+container.id, port_map)

    return "run successful"

def stop_command(req):
    if "app_name" not in req:
        return "run: app_name required"
    app_name = req["app_name"]
    if app_name not in cloud_info:
        return "run: app_name not found, must create app first"

    if "worker_id" not in req:
        return "stop: worker_id required"
    worker_id = req["worker_id"]

    if worker_id not in cloud_info[app_name]["containers"]:
        return "worker_id "+worker_id+" not found in app "+app_name

    container,_ = cloud_info[app_name]["containers"][worker_id]

    extra = ""
    try: container.kill()
    except: extra = " (container already dead)"

    del cloud_info[app_name]["containers"][worker_id]
    etcd_client.delete("/mycloud/"+app_name+"/containers/"+container.id)

    return "stop successful (worker_id-"+worker_id+")" + extra

def info_command(req):
    strs = []
    def pretty(d, indent=0):
       for key, value in d.items():
          strs.append('\t' * indent + str(key))
          if isinstance(value, dict):
             pretty(value, indent+1)
          else:
             strs.append('\t' * (indent+1) + str(value))
    pretty(cloud_info)
    return "\n".join(strs)


# FLASK
#-----------------------------------------------------------------------------------------------------

app = Flask(__name__)

@app.route("/", methods=["POST"])
def only_route():
    req = request.get_json()
    command = req['command']
    if "create" == command:
        return create_command(req)
    elif "run" == command:
        return run_command(req)
    elif "stop" == command:
        return stop_command(req)
    elif "info" == command:
        return info_command(req)
    else:
        return "command not found"

app.run(host='0.0.0.0', port=int(config["MANAGER_SERVER"]["Port"]))
