#!/usr/bin/env python3

help_string = (
    "usage: ./mycloud <command> [args]\n"
    "\n"
    "  ./mycloud create <app_name>\n"
    "  ./mycloud run"
)

# THIS IS THE CLI

import requests
import configparser
import sys

config = configparser.ConfigParser()
config.read("config.ini")

def call_cloud(req_data):
    url = "http://127.0.0.1:" + config["MANAGER_SERVER"]["Port"] + "/"
    r = requests.post(url, json=req_data)
    print(r.text)

args = sys.argv[1:]

if len(args) < 2:
    print("you need to enter a command") # TODO: fix it
    sys.exit(1)

if args[0] == "create":
    req_to_cloud = {"command":"create", "app_name":args[1]}
    call_cloud(req_to_cloud)
elif args[0] == "run":
    port_map = "{"+args[3]+"}"
    cmd = args[4]
    req_to_cloud = {"command":"run", "app_name":args[1], "port_map":port_map, "command_string":cmd}
    call_cloud(req_to_cloud)
