#!/usr/bin/env python3

# THIS IS THE CLI

import requests

import sys
args = sys.argv[1:]

if len(args) < 2:
    print("you need to enter a command") # TODO: fix it
    sys.exit(1)

if args[0] == "create":
    req_to_cloud = {"command": "create", "app_name": args[1]}
    requests.post("localhost:8000", data=req_to_cloud)
